// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWvB2f0eoYlo7IGRFb97747VzVoqzDPw4',
    appId: '1:452949840056:web:414b256b21c392b6db244d',
    messagingSenderId: '452949840056',
    projectId: 'invoice-app-c772e',
    authDomain: 'invoice-app-c772e.firebaseapp.com',
    storageBucket: 'invoice-app-c772e.appspot.com',
    measurementId: 'G-RQCHHP92NE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjnPEB7nmVsEd1znha1Bwj9H7Q0sCfaBs',
    appId: '1:452949840056:android:1aafa79fdfcbbdfadb244d',
    messagingSenderId: '452949840056',
    projectId: 'invoice-app-c772e',
    storageBucket: 'invoice-app-c772e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1QxPZiZLTZTJCB6Z6jvVijIk5XTktg44',
    appId: '1:452949840056:ios:4b97a1b6f3ec9b8edb244d',
    messagingSenderId: '452949840056',
    projectId: 'invoice-app-c772e',
    storageBucket: 'invoice-app-c772e.appspot.com',
    iosBundleId: 'com.example.invoiceGenerator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1QxPZiZLTZTJCB6Z6jvVijIk5XTktg44',
    appId: '1:452949840056:ios:d8a2110e73b0c3ccdb244d',
    messagingSenderId: '452949840056',
    projectId: 'invoice-app-c772e',
    storageBucket: 'invoice-app-c772e.appspot.com',
    iosBundleId: 'com.example.invoiceGenerator.RunnerTests',
  );
}
